### ISSUE TITLE
rust build error

### ISSUE THREAD

**Issue by ramicaza** [allada/lighthouse-beacon-snapshot#1]
FYI I get this error when building the etc-snapshot.

https://github.com/sigp/lighthouse/issues/3654

Downgrading to rust 1.64.0 seems to fix it for now!

So you might want to update your script to forcefully install rust 1.64.0 using rustup

`rustup install 1.64.0`

then

`rustup default 1.64.0-aarch64-unknown-linux-gnu`

**Comment by allada** [comment]
Thank you for the notice and doing the work to figure out what specific version to use, it saved me a bit of time :-)

**Comment by ramicaza** [comment]
Of course, thanks for putting together the amazing bsc/eth snapshot repos!!
